name: Robot Scraper Subuh

# KAPAN ROBOT INI HARUS BANGUN?
on:
  schedule:
    # Waktu di GitHub memakai jam London (UTC).
    # Jam 5 Pagi WIB (Jakarta) = Jam 22:00 UTC (Malam sebelumnya).
    - cron: '15 22 * * *'
  workflow_dispatch: # Ini memunculkan tombol rahasia untuk tes manual

# APA YANG HARUS DILAKUKAN ROBOT?
jobs:
  sedot_data_harian:
    runs-on: ubuntu-latest
    permissions:
      contents: write 
    
    steps:
    - name: 1. Buka Pintu Gudang (Checkout)
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: 2. Siapkan Mesin Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: 3. Pasang Onderdil (Install Library)
      run: pip install --upgrade yfinance pandas pytz requests urllib3 ipython jinja2 pandas-datareader
      
    - name: 4. Tekan Tombol RUN Mesin Scraper & Analisis!
      env:
        TGRAM_COUNTER: ${{ secrets.TGRAM_COUNTER }}
        TGRAM_TAG: ${{ secrets.TGRAM_TAG }}
      run: |
        python scraper_mesin.py
        python analisis_auto.py

    - name: 5. Simpan Hasil CSV Kembali ke Gudang
      run: |
        git config --global user.name "Robot Scraper"
        git config --global user.email "robot@github.com"
        git add pressure_6mo_history.csv
        git commit -m "Update data harian otomatis jam 5 Pagi" || exit 0
        git push
